High jumping
Badtz13/bone pull request #13
Opened 2024-03-04 04:28 UTC by Badtz13

- implements a bone effect called high_jumping, which can be applied to boots
- adds a mixin that ticks on living entities to see if they are using any enchanted items, and apply their effects once per second
- corrects issues with bone effect level labeling, generates enchanted books for the associated levels

2024-03-04 04:34 UTC, Badtz13 commented
I'd like some input on my mixin, I'm not sure how efficient / extensible it is. 

I'd also like to do some brainstorming about how the effect showing works. Right now, the jump boost effect is shown while you are in your inventory, despite hideIcon flags, as hideIcon only hides the icon during normal gameplay. It seems technically possible to add an override mixin to AbstractInventoryScreen to either filter to hide the status effects that have hideIcon, but since this is changing vanilla gameplay markedly, it seems good to check in about.

2024-03-04 06:12 UTC, Badtz13 commented
The actual effects are more of a proof of concept, the main thing is that we can easily add status effect based bone effects easily.

2024-03-05 00:00 UTC, langedev requested changes

2024-03-05 00:54 UTC, Badtz13 commented
- create BoneType package with Generic and StatusEffect types

2024-03-05 03:16 UTC, langedev requested changes

2024-03-05 03:27 UTC, langedev approved these changes

2024-03-05 03:28 UTC, merged